[package]
name = "grust"
version = "0.2.1"
edition = "2024"

[lib]
crate-type = ["cdylib"] # Compile this crate to a dynamic C library.

[dependencies]
# Update to the latest stable gdext when possible.
godot = { git = "https://github.com/godot-rust/gdext", tag = "v0.4.5" }
bevy_ecs = "~0.18.0"
hexx = {version = "~0.24.0", default-features = false, features = ["bevy_ecs", "mesh"]}

[features]
# Ensure that enabling `nothreads` for the main crate also enables
# that feature for other crates.
wasm = [
    "godot/api-custom",
    "godot/experimental-wasm",
    "godot/lazy-function-tables",
]
# Markers
nothreads = []
threads = []

wasm-nothreads = ["wasm", "nothreads", "godot/experimental-wasm-nothreads"]
